### ISSUE TITLE
Qestions about initializing trianable weights

### ISSUE THREAD

**Issue by zywang1603** [KoertS/KNMI_Internship_GANs#1]
Hi Koert
I am Zhiyi who is trying to run your project. May I ask in which file, and how do you initialize your trainable weights? And what is 'server' in your configuration? Another issue is that, when I run 'testrun.py', I found it works well on CPU, but the loss became nan when I switched to GPU. Did you face the same problem?
I would really appreciate it if you could help me. Thank you very much

**Comment by KoertS** [comment]
Hey Zhiyi,

The weights are initialized when creating the GAN model in [model_builder.py](https://github.com/KoertS/precipitation-nowcasting-using-GANs/blob/main/precipitation_forecasting/model_builder.py).  Tensorflow's default weight initializer was used. 

The "server" in the configuration is just a variable that I wanted to log in weights and biases. It indicates on what remote server I ran the model on, you can leave this out of the config if you want.

I do not know why your loss becomes nan when switching to GPU, I do not recall running into that problem. Does it happen on every run? 

I hope this helps! If you have anymore questions feel free to ask

**Comment by zywang1603** [comment]
> Hey Zhiyi,
> 
> The weights are initialized when creating the GAN model in [model_builder.py](https://github.com/KoertS/precipitation-nowcasting-using-GANs/blob/main/precipitation_forecasting/model_builder.py). Tensorflow's default weight initializer was used.
> 
> The "server" in the configuration is just a variable that I wanted to log in weights and biases. It indicates on what remote server I ran the model on, you can leave this out of the config if you want.
> 
> I do not know why your loss becomes nan when switching to GPU, I do not recall running into that problem. Does it happen on every run?
> 
> I hope this helps! If you have anymore questions feel free to ask

Hi Koert
Thank you very much for your reply. It seems to be some technincal issues with the GPU that make the code fail to run. Annother problem I am facing now is , when I use AENN and convGRU as generator, and set the normalization method as 'None', all the output pixels are less than or equal to 1mm/h, even if the actual precipitation rate is very high(just as the picture below). I suspect there are some codes that set all value larger than 1 as 1, but I am not sure. May I ask is it the case? or did you face similar problems? Thank you very much.
![image](https://user-images.githubusercontent.com/79249340/159673677-403d4a8b-b09b-4c26-b86a-fa6480ec37ce.png)

**Comment by zywang1603** [comment]
> 

Hi Koert
Thank you very much for your reply. My loss become nan on every run on GPU. Maybe it is the environment configuration issue. May I ask do you have the configuration file(yml) for successful running on GPU? Thank you very much

**Comment by zywang1603** [comment]
> I have found the issue. It is a congifuration problem, my cuda and cudnn does not match tensorflow version. I have solved the problem, and it can now work on GPU

**Comment by KoertS** [comment]
Hey Zhiyi, 
Glad that you found the solution!
